import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

/*
 * ESLint's flat config. Configured here rather than left to `next lint`, which
 * is deprecated in Next 15 and, with no config present, opens an interactive
 * setup prompt — so `pnpm lint` on a fresh checkout asked a question and
 * exited 1 instead of linting anything. `pnpm lint` now runs eslint directly,
 * and CI runs it too.
 *
 * FlatCompat is what wraps the shareable next config, which is still written
 * in the older eslintrc format.
 */
const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  {
    ignores: [
      // Every build output directory, not just the default one: distDir is
      // overridable (NEXT_DIST_DIR), and an unignored `.next-*` left behind by
      // a one-off build buries real findings under thousands of generated ones.
      ".next*/**",
      "node_modules/**",
      // Rewritten by `next build`; not ours to edit.
      "next-env.d.ts",
      // Generated by `convex dev`; not ours to lint.
      "convex/_generated/**",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      // Unused arguments are how a handler signature documents what it is
      // given; a leading underscore marks the ones deliberately ignored.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
];

export default config;
